SELECT ?date ?datagouvcount
WITH {
  SELECT (COUNT(*) AS ?datagouvcount) WHERE {
    SELECT ?datagouvid ?item
      WHERE {
        ?item wdt:P3206 ?datagouvid .
       }
   }
} AS %datagouvid
WHERE {
  {
    BIND(NOW() AS ?date)
    INCLUDE %datagouvid
  }
}
