version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Get the data
          command: |
            cd wiki-data-gouv
            ./getdata.sh
