version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps: 
      - run:
          name: Installs
          command: |
            apt install ssh
            apt install git
      - checkout
      - run:
          name: Get the data
          command: |
            cd organisations-data-gouv
            ./getdata.sh
