version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps: 
      - checkout
      - run:
          name: Get the data
          command: |
            git clone https://github.com/pachevalier/organisations-data-gouv
            cd organisations-data-gouv
            git checkout $CIRCLE_BRANCH
            ./getdata.sh
